version: "3.9"

services:
  database:
    image: ankane/pgvector
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - "8488:8488"
    environment:
      - POSTGRES_HOST=database
      - DEBUG=true
      - WHATSAPP_TOKEN=EAAblah
      - WHATSAPP_VERIFY_TOKEN=blah
      - KHOJ_API_URL=http://localhost:42110
      - KHOJ_API_CLIENT_ID=blah
      - KHOJ_API_CLIENT_SECRET=blah
    depends_on:
      - database
    volumes:
      - flint_models:/root/.cache/torch/sentence_transformers

volumes:
  postgres_data:
  flint_models:
